-- Crear la tabla de socios si no existe
CREATE TABLE IF NOT EXISTS socios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    nombre TEXT NOT NULL,
    dni TEXT UNIQUE NOT NULL,
    estado TEXT DEFAULT 'activo'
);

-- Crear la tabla de cobranzas si no existe
CREATE TABLE IF NOT EXISTS cobranzas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    socio_id BIGINT REFERENCES socios(id),
    monto NUMERIC NOT NULL,
    fecha DATE DEFAULT CURRENT_DATE,
    usuario_cobrador TEXT NOT NULL
);
